name: Deploy on vps

on:
  push:
    branches:
      - main

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Deployment job
  deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Connect to vps & run docker
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     run: |
      #     docker compose down
      #     docker compose up -d --build

      - name: Connect to vps & run docker
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "."
          SCRIPT_BEFORE: |
            cd traefik
            docker compose down
          SCRIPT_AFTER: |
            cd traefik
            docker compose up --build -d
